# -*- coding: utf-8 -*-
"""classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hPLdScFb8_5hYrv3h04qB0tGs-JELYL7
"""

from transformers import pipeline

MODEL_NAME = "bert-base-uncased"

_classifier = pipeline(
    "text-classification",
    model=MODEL_NAME,
    tokenizer=MODEL_NAME,
)

def classify_ambiguity(sentence: str) -> dict:

    result = _classifier(sentence)[0]

    return {
        "input": sentence,
        "label": result["label"],
        "confidence": result["score"],
        "model": MODEL_NAME,
        "is_ambiguous": None,
    }