# -*- coding: utf-8 -*-
"""localizer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pfkea4U5d3138c-4iIK76mUbQdsfGRpU
"""

from transformers import pipeline

MODEL_NAME = "dslim/bert-base-NER"

_ner = pipeline(
    "token-classification",
    model=MODEL_NAME,
    tokenizer=MODEL_NAME,
    aggregation_strategy="simple",
)


def localize_terms(sentence: str) -> dict:

    ner_results = _ner(sentence)

    occupations = []
    pronouns = []

    for entity in ner_results:
        word = entity["word"]
        label = entity["entity_group"]

        if label in ["PER", "ORG", "MISC"]:
            continue

        if word.lower() in {"they", "them", "their"}:
            pronouns.append({
                "text": word,
                "start": entity["start"],
                "end": entity["end"],
                "label": "GENDER_NEUTRAL_PRONOUN",
            })

    OCCUPATIONS = {
        "doctor",
        "nurse",
        "engineer",
        "teacher",
        "lawyer",
        "programmer",
        "manager",
        "scientist",
    }

    tokens = sentence.split()

    for i, token in enumerate(tokens):
        if token.lower().strip(".,!?") in OCCUPATIONS:
            occupations.append({
                "text": token,
                "index": i,
                "label": "OCCUPATION",
            })

    return {
        "occupations": occupations,
        "pronouns": pronouns,
        "raw_ner": ner_results,
        "model": MODEL_NAME,
    }